import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface ChatMessage {
  id: string;
  role: 'user' | 'ai';
  content: string;
  imageUrl?: string;
}

@Component({
  selector: 'app-chat-message',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="flex w-full mb-6" [ngClass]="{'justify-end': message.role === 'user', 'justify-start': message.role === 'ai'}">
      
      <!-- User Message -->
       @if (message.role === 'user') {
        <div class="max-w-[80%] md:max-w-[70%]">
          <div class="bg-zinc-100 dark:bg-zinc-800 text-zinc-900 dark:text-zinc-100 px-5 py-3 rounded-2xl rounded-tr-sm shadow-sm">
            <p class="whitespace-pre-wrap">{{ message.content }}</p>
          </div>
        </div>
       }
       @if (message.role === 'ai') {
      <!-- AI Message -->
      <div class="flex gap-4 max-w-[90%] md:max-w-[80%]">
        <!-- Avatar/Icon -->
        <div class="shrink-0 w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white text-xs font-bold">
          AI
        </div>

        <div class="flex flex-col gap-3">
          <!-- Text Content -->
           @if (message.content) {
          <div class="text-zinc-800 dark:text-zinc-200">
            <p>{{ message.content }}</p>
          </div>
          }

          @if(message.imageUrl){
          <!-- Generated Image -->
          <div class="relative group rounded-xl overflow-hidden border border-zinc-200 dark:border-zinc-700 shadow-sm bg-zinc-50 dark:bg-zinc-900">
             <img [src]="message.imageUrl" 
                  (error)="onImageError($event)" 
                  (load)="onImageLoad()"
                  alt="Generated by AI" 
                  class="max-w-sm w-full h-auto object-cover" />
             
             <!-- Draw Button Overlay (or below) -->
             <div class="p-3 bg-white dark:bg-zinc-900 border-t border-zinc-200 dark:border-zinc-800 flex justify-end">
               <button (click)="onDraw()" class="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors">
                 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-pen-tool"><path d="m12 19 7-7 3 3-7 7-3-3z"/><path d="m18 13-1.5-7.5L2 2l3.5 14.5L13 18l5-5z"/><path d="m2 2 7.586 7.586"/><circle cx="11" cy="11" r="2"/></svg>
                 Disegna
               </button>
             </div>
          </div>
          }
        </div> 
      </div>
      }
    </div>
  `,
  styles: []
})
export class ChatMessageComponent {
  @Input({ required: true }) message!: ChatMessage;
  @Output() draw = new EventEmitter<string>();

  onDraw() {
    if (this.message.imageUrl) {
      this.draw.emit(this.message.imageUrl);
    }
  }

  onImageError(event: Event) {
    console.error('[ChatMessage] Error loading image:', event);
  }

  onImageLoad() {
    console.log('[ChatMessage] Image loaded successfully:', this.message.imageUrl);
  }
}
